FROM python:3.13-slim-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl && \
    # Clean up to reduce image size
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir requests

CMD ["/bin/bash"]